version: '3.3'

services:
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - '4566:4566'
    environment:
      - SERVICES=lambda,sns
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'