version: '3.3'

services:
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - '4566:4566'
    environment:
      - SERVICES=lambda,sns
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  db-pomca:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db-pomca-data:/var/lib/postgresql/data
volumes:
  db-pomca-data:
    driver: local
